In [245]:
import numpy as np

In [246]:
class Board:
    def __init__(self, state = np.empty((9, 9), dtype=int)):
        self.board = state
        self.nextState = []
    def setBoard(self, row, column, number):
        copy = np.copy(self.board)
        copy[row, column] = number
        nextState = Board(copy)
        self.nextState.append(nextState)
        return nextState

In [247]:
def bfs(graph):
    queue, path = graph, []
    row, column = graph[0].board.shape
    while queue:
        vertex = queue.pop(0)
        path.append(vertex)
        if np.count_nonzero(vertex.board==0) == 0:
            return path
        for i in range(row):
            for j in range(column):
                if vertex.board[i,j] == 0:
                    for k in range(1,10):
                        copy = np.copy(vertex.board)
                        row_ele = copy[i, :].tolist()
                        row_col = copy[:, j].tolist()
                        if k not in row_ele or k not in row_col:
                            neighbor = vertex.setBoard(i,j,k)
                            queue.append(neighbor)
                            #print("add done")
    return path
                            
                            
    

In [248]:
sudoku = Board(np.array([[8, 0, 0, 6, 0, 0, 0, 2, 0],
                         [0, 0, 3, 0, 9, 4, 6, 0, 0],
                         [7, 0, 0, 5, 0, 0, 0, 9, 3],
                         [9, 0, 0, 8, 6, 0, 5, 0, 0],
                         [4, 8, 0, 3, 0, 9, 0, 6, 1],
                         [0, 0, 6, 0, 4, 2, 0, 0, 9],
                         [6, 9, 0, 0, 0, 5, 0, 0, 2],
                         [0, 0, 4, 9, 1, 0, 3, 0, 0],
                         [0, 1, 0, 0, 0, 7, 0, 0, 6],]))

In [249]:
res = [sudoku]

In [250]:
bfs_res = bfs(res)

[3, 4, 5, 7]
01
[[8 3 0 6 0 0 0 2 0]
 [0 0 3 0 9 4 6 0 0]
 [7 0 0 5 0 0 0 9 3]
 [9 0 0 8 6 0 5 0 0]
 [4 8 0 3 0 9 0 6 1]
 [0 0 6 0 4 2 0 0 9]
 [6 9 0 0 0 5 0 0 2]
 [0 0 4 9 1 0 3 0 0]
 [0 1 0 0 0 7 0 0 6]]
[1, 5, 7, 9]
02
[[8 3 1 6 0 0 0 2 0]
 [0 0 3 0 9 4 6 0 0]
 [7 0 0 5 0 0 0 9 3]
 [9 0 0 8 6 0 5 0 0]
 [4 8 0 3 0 9 0 6 1]
 [0 0 6 0 4 2 0 0 9]
 [6 9 0 0 0 5 0 0 2]
 [0 0 4 9 1 0 3 0 0]
 [0 1 0 0 0 7 0 0 6]]
[5, 7]
04
[[8 3 1 6 5 0 0 2 0]
 [0 0 3 0 9 4 6 0 0]
 [7 0 0 5 0 0 0 9 3]
 [9 0 0 8 6 0 5 0 0]
 [4 8 0 3 0 9 0 6 1]
 [0 0 6 0 4 2 0 0 9]
 [6 9 0 0 0 5 0 0 2]
 [0 0 4 9 1 0 3 0 0]
 [0 1 0 0 0 7 0 0 6]]
[]
05


In [251]:
len(bfs_res)

4

In [252]:
bfs_res[0].board

array([[8, 3, 1, 6, 5, 0, 0, 2, 0],
       [0, 0, 3, 0, 9, 4, 6, 0, 0],
       [7, 0, 0, 5, 0, 0, 0, 9, 3],
       [9, 0, 0, 8, 6, 0, 5, 0, 0],
       [4, 8, 0, 3, 0, 9, 0, 6, 1],
       [0, 0, 6, 0, 4, 2, 0, 0, 9],
       [6, 9, 0, 0, 0, 5, 0, 0, 2],
       [0, 0, 4, 9, 1, 0, 3, 0, 0],
       [0, 1, 0, 0, 0, 7, 0, 0, 6]])

array([[8, 3, 0, 6, 0, 0, 0, 2, 0],
       [0, 0, 3, 0, 9, 4, 6, 0, 0],
       [7, 0, 0, 5, 0, 0, 0, 9, 3],
       [9, 0, 0, 8, 6, 0, 5, 0, 0],
       [4, 8, 0, 3, 0, 9, 0, 6, 1],
       [0, 0, 6, 0, 4, 2, 0, 0, 9],
       [6, 9, 0, 0, 0, 5, 0, 0, 2],
       [0, 0, 4, 9, 1, 0, 3, 0, 0],
       [0, 1, 0, 0, 0, 7, 0, 0, 6]])